image: node:8.9.0

stages:
  - build
  - lint
  - test

before_script:
  - npm install
  - apt-get update
  - apt-get install -y netcat


# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

test:
  script:
   - npm run build
   - npm run test

lint:
  script:
   - npm run lint

build:
  script:
   - npm run build
   - npm run start:production
